### ISSUE TITLE
get fails with scoped packages

### ISSUE THREAD

**Issue by mjackson** [npm/npm-registry-client#123] opened 2015-11-08 08:57 UTC
I can't seem to use the `get` method to fetch package info about scoped packages. In my node prompt:

```log
> var RegistryClient = require('npm-registry-client')
> var client = new RegistryClient
undefined
> client.get('https://registry.npmjs.org/@cycle/core', { timeout: 5000 }, function (error) { console.log(error) })
info attempt registry request try #1 at 12:55:30 AM
http request GET https://registry.npmjs.org/@cycle/core
http 404 https://registry.npmjs.org/@cycle/core
{ [Error: Not found : @cycle] pkgid: '@cycle', statusCode: 404, code: 'E404' }
```

Am I doing something wrong?

**Comment by othiym23** [comment] 2015-11-08 16:50
`npm-registry-client` is due for a rewrite, for this reason and many others. If you look at how npm calls into it, you'll see that scoped package names are encoded such that `/` becomes `%2f` (due to legacy CouchDB-related reasons). Also, you're going to need to pass along a bearer token as `auth` in the request's `options` parameter to get metadata on scoped packages. It _should_ work without auth for scoped public packages, but it definitely won't for private.

As this is all by design, I'm going to close this issue, but rest assured that a new major version of `npm-registry-client` with a much less obtuse API is a high priority for the team.

**Closed by othiym23** 2015-11-08 16:50 UTC

**Comment by mjackson** [comment] 2015-11-08 17:01
Thank you for the explanation, @othiym23. For now I'm only interested in getting info on public scoped packages. Is there a workaround for the encoding issue? From the error message, it looks like the registry is only recognizing `@cycle` as the package name, not `@cycle/core`.

**Comment by mjackson** [comment] 2015-11-08 17:47
Perhaps there is a straight-up HTTP endpoint I could hit to get data about packages? I'm only ever doing `GET`s, so I actually don't need most of the fancy stuff npm-registry-client gives me.

**Comment by mjackson** [comment] 2015-11-08 18:25
Ah, nm. I just followed the source and found out how to call it. Thanks again, @othiym23!

**Comment by tiansijie** [comment] 2016-03-08 04:02
@mjackson could you share how you call it with scoped packages? thanks

**Comment by mjackson** [comment] 2016-03-08 19:45
@tiansijie https://github.com/mjackson/npm-http-server/blob/b4719424f168648e8cf164cc1abea3c44237b43e/modules/getPackageInfo.js#L9-L23

That's how you encode the package name in the registry URL.

**Comment by tiansijie** [comment] 2016-03-08 19:50
@mjackson thanks!
